/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "LlmCalc": import("@cloudflare/workers-types").Service
    "McpLimit": import("@cloudflare/workers-types").RateLimit
  }
}

import "sst"
export {}